### ISSUE TITLE
Question About Getting Bulk Playlist Data

### ISSUE THREAD

**Issue by tobydodds** [lmcalpin/dogstarrelay#1]
I work for the non-profit record label Smithsonian Folkways Recordings.  Please contact me if you can assist us in capturing playlist data in bulk going back to 2010.  I've been studying your code but can't crack it.  Thanks!  Toby Dodds - doddst@si.edu.

**Comment by lmcalpin** [comment]
The code just collects the data from http://www.dogstarradio.com/, so you might contact that site's owner.
